#!/bin/bash

source=test.c
dependencies=test.o.d
obj=test.o
bin=test

ndk=${src}/android-ndk-r9d
ndk_clang=${ndk}/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin
ndk_gcc=${ndk}/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64
ndk_system=${ndk}/platforms/android-19/arch-arm
common_flags="-gcc-toolchain ${ndk_gcc} -target armv5te-none-linux-androideabi"

${ndk_clang}/clang++ ${common_flags} -I${ndk_system}/usr/include -march=armv5te -mtune=xscale -msoft-float -mthumb -g -c ${source} -o ${obj}
${ndk_clang}/clang++ ${common_flags} --sysroot=${ndk_system} -Wl,-rpath-link=${ndk_system}/usr/lib -o ${bin} ${obj} -lgcc -lc -lm

