#!/bin/bash

ndk=${android_ndk}
ndk_gcc=${ndk}/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64
ndk_system=${ndk}/platforms/android-19/arch-arm
ndk_libstdcpp=${ndk}/sources/cxx-stl/gnu-libstdc++/4.6
common_flags="--sysroot=${ndk_system}"
appended_flags=

if [ ${1} = compile ] ; then
  flags="${common_flags} -march=armv5te -mtune=xscale -msoft-float -mthumb -isystem ${ndk_system}/usr/include -isystem ${ndk_libstdcpp}/include -I${ndk_libstdcpp}/libs/armeabi/include -I${ndk_libstdcpp}/include/backward -I${android_source}/system/core/include -I${android_source}/frameworks/native/include -I${android_source}/frameworks/av/include -I${android_source}/hardware/libhardware/include -I${android_source} -DANDROID -DANDROID_r4_4_2 -DNDEBUG"
elif [ ${1} = link ] ; then
  flags="${common_flags} -Wl,-rpath-link=${ndk_system}/usr/lib"
  appended_flags="${ndk_libstdcpp}/libs/armeabi/libgnustl_static.a -lgcc -lc -lm"
else
  echo "${0}: specify compile or link"
  exit 1
fi

shift

exec ${ndk_gcc}/bin/arm-linux-androideabi-g++ ${flags} ${@} ${appended_flags}

